resolver: lts-7.9

packages:
- '.'
- location:
    git: https://github.com/serokell/universum
    commit: d347ccf3605d0851dd0f7046fe63f364510ef1a0
  extra-dep: true
- location:
    git: https://github.com/serokell/log-warper.git
    commit: e05d74587ff9270891a3e57f1f15d9e91c8d2c83
  extra-dep: true
- location:
    git: https://github.com/domenkozar/hs-ed25519.git
    commit: 96e5db162d88482bc0e120dc61cadd45c168c275
  extra-dep: true

nix:
  shell-file: shell.nix

extra-deps:
- pretty-tree-0.1.0.0
- serokell-util-0.1.3.0
- time-units-1.0.0
- aeson-extra-0.4.0.0
- data-msgpack-0.0.8
- recursion-schemes-5
